version: "3.8"
services:
  frontend:
    container_name: snap-sorter-frontend-prod
    build:
      context: ./frontend
      dockerfile: prod.Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    volumes:
      - ./frontend/src:/app/src
    image: snap-sorter-frontend-prod
