version: "3.8"
services:
  frontend:
    container_name: snap-sorter-frontend-dev
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 5173:5173
    volumes:
      - ./frontend/src:/app/src
    image: snap-sorter-frontend-dev
