name: snap-sorter-winenv-py310
channels:
  - pytorch
  - defaults
dependencies:
  - appdirs=1.4.4
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - colorama=0.4.6
  - comm=0.1.2
  - cpuonly=2.0
  - cryptography=39.0.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - executing=0.8.3
  - filelock=3.9.0
  - freetype=2.12.1
  - giflib=5.2.1
  - icc_rt=2022.1.0
  - idna=3.4
  - intel-openmp=2021.4.0
  - ipykernel=6.19.2
  - ipython=8.12.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.1.1
  - jpeg=9e
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - lerc=3.0
  - libdeflate=1.17
  - libffi=3.4.2
  - libpng=1.6.39
  - libsodium=1.0.18
  - libtiff=4.5.0
  - libuv=1.44.2
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpmath=1.2.1
  - nest-asyncio=1.5.6
  - networkx=2.8.4
  - numpy=1.23.5
  - numpy-base=1.23.5
  - openssl=1.1.1t
  - packaging=23.0
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - platformdirs=2.5.2
  - pooch=1.4.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=23.0.0
  - pysocks=1.7.1
  - python=3.10.11
  - python-dateutil=2.8.2
  - pytorch=2.0.0
  - pytorch-mutex=1.0
  - pywin32=305
  - pyzmq=23.2.0
  - requests=2.28.1
  - scikit-learn=1.2.2
  - scipy=1.10.1
  - setuptools=66.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - sympy=1.11.1
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - torchaudio=2.0.0
  - torchvision=0.15.0
  - tornado=6.2
  - traitlets=5.7.1
  - typing_extensions=4.5.0
  - tzdata=2023c
  - urllib3=1.26.15
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - wheel=0.38.4
  - win_inet_pton=1.1.0
  - xz=5.2.10
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - black==23.3.0
      - click==8.1.3
      - facenet-pytorch==2.5.3
      - mypy-extensions==1.0.0
      - pathspec==0.11.1
      - tomli==2.0.1

